"""
Author: Andres Zibula

Github: https://github.com/andres-zibula/geekforgeeks-problems-solved

Problem link: http://practice.geeksforgeeks.org/problems/pell-number/0

Description: Pell numbers are numbers that are similar to the Fibonacci numbers and are generated by below formula
Pn = 2*Pn-1 + Pn-2
"""

pellDict = {0: 0, 1: 1}

def pellNumber(n):
	if n in pellDict:
		return pellDict[n]
	else:
		return 2*pellNumber(n-1) + pellNumber(n-2)

for i in range(101):
	pellDict[i] = pellNumber(i)

T = int(input())

for _ in range(T):
    n = int(input())
    print(pellDict[n])